# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'V-Star' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 4.7.3'
pod 'JXSegmentedView'
 pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
 pod 'SnapKit', '~> 5.0.0'
pod 'MJRefresh'
  # Pods for V-Star
pod 'AliyunVideoSDKStd'
pod 'QuCore-ThirdParty'
pod 'VODUpload'
pod 'AliyunOSSiOS'
pod 'AlivcConan'
pod 'SDWebImage', '~> 5.0'
pod 'WMPageController', '2.3.0'
pod 'SwiftyJSON'
pod 'WechatOpenSDK', '1.8.5'
#pod 'WechatKit'
end
