source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'V-Star' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 4.7.3'
pod 'JXSegmentedView'
 pod 'SnapKit', '~> 5.0.0'
pod 'MJRefresh'
pod 'AFNetworking', '~> 3.0'
  # Pods for V-Star
pod 'AliyunVideoSDKStd'
pod 'VODUpload'
pod 'AliyunOSSiOS'
pod 'SDWebImage', '~> 5.0'
pod 'WMPageController', '2.3.0'
pod 'SwiftyJSON'
pod 'WechatOpenSDK', '1.8.5'
pod 'AlivcConan'
pod 'QuCore-ThirdParty'

#pod 'AlivcConan'
#pod 'QuCore-ThirdParty'
end

